#!/bin/bash
# find . -type d ! -path "." ! -path ".." -exec sh -c 'printf "%s\n" "$0" | grep -q "^\." && echo "$0"' {} \; | wc -l
find . -mindepth 1 -maxdepth 1 -type d -not -name "." -not -name ".." | wc -l
